name: Kevin och Mikael
on: push
jobs: 
  build: 
    name: Spacepark build
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1
      with: 
        dotnet-version: 5.0.x
      
    - name: Restore
      run: dotnet restore Source/SpacePark.sln
    - name: Build
      run: dotnet build --no-build --verbosoity nomral Source/SpacePark.sln
    - name: Testing
      run: dotnet test --no-build --verbosity nomral Source/SpacePark.sln 
 
